// contact list
export const GET_CONTACT_LIST = 'GET_CONTACT_LIST'
export const GET_CONTACT_LIST_SUCCESS = 'GET_CONTACT_LIST_SUCCESS'
export const GET_CONTACT_LIST_FILTER = 'GET_CONTACT_LIST_FILTER'

// sign_up
export const SIGN_UP_START = 'SIGN_UP_START'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'
export const SIGN_UP_CLEAR = 'SIGN_UP_CLEAR'

// sign_in
export const SIGN_IN_START = 'SIGN_IN_START'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'
export const SIGN_IN_CLEAR = 'SIGN_IN_CLEAR'

export const LOG_OUT = 'LOG_OUT'

// Get users information
export const GET_USER_INFO = 'GET_USER_INFO'
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS'
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE'
export const GET_USER_INFO_CLEAR = 'GET_USER_INFO_CLEAR'

// Get users information
export const GET_MEDIA = 'GET_MEDIA'
export const GET_MEDIA_CLEAR = 'GET_MEDIA_CLEAR'

// Update users information
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE'
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS'
export const UPDATE_USER_PROFILE_FAILURE = 'UPDATE_USER_PROFILE_FAILURE'
export const UPDATE_USER_PROFILE_CLEAR = 'UPDATE_USER_PROFILE_CLEAR'

// verification
export const CHECK_VERIFICATION_CODE_START = 'CHECK_VERIFICATION_CODE_START'
export const CHECK_VERIFICATION_CODE_SUCCESS = 'CHECK_VERIFICATION_CODE_SUCCESS'
export const CHECK_VERIFICATION_CODE_FAILURE = 'CHECK_VERIFICATION_CODE_FAILURE'
export const CHECK_VERIFICATION_CODE_CLEAR = 'CHECK_VERIFICATION_CODE_CLEAR'

// update attributes
export const UPDATE_USER_ATTRIBUTES_START = 'UPDATE_USER_ATTRIBUTES_START'
export const UPDATE_USER_ATTRIBUTES_SUCCESS = 'UPDATE_USER_ATTRIBUTES_SUCCESS'
export const UPDATE_USER_ATTRIBUTES_FAILURE = 'UPDATE_USER_ATTRIBUTES_FAILURE'
export const UPDATE_USER_ATTRIBUTES_CLEAR = 'UPDATE_USER_ATTRIBUTES_CLEAR'
export const FALSE_FLAGS_IN_USER = 'FALSE_FLAGS_IN_USER'

// create password
export const CREATE_USER_PASSWORD_START = 'CREATE_USER_PASSWORD_START'
export const CREATE_USER_PASSWORD_SUCCESS = 'CREATE_USER_PASSWORD_SUCCESS'
export const CREATE_USER_PASSWORD_FAILURE = 'CREATE_USER_PASSWORD_FAILURE'
export const CREATE_USER_PASSWORD_CLEAR = 'CREATE_USER_PASSWORD_CLEAR'

// reset password
export const RESET_PASSWORD_START = 'RESET_PASSWORD_START'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE'
export const RESET_PASSWORD_CLEAR = 'RESET_PASSWORD_CLEAR'

export const GET_ROOM_START = 'GET_ROOM_START'
export const GET_ROOM_SUCCESS = 'GET_ROOM_SUCCESS'
export const GET_ROOM_FAILURE = 'GET_ROOM_FAILURE'

export const GET_USER_MESSAGES_START = 'GET_USER_MESSAGES_START'
export const GET_USER_MESSAGES_SUCCESS = 'GET_USER_MESSAGES_SUCCESS'
export const GET_USER_MESSAGES_FAILURE = 'GET_USER_MESSAGES_FAILURE'

export const SEND_USER_MESSAGE_START = 'SEND_USER_MESSAGE_START'
export const SEND_USER_MESSAGES_SUCCESS = 'SEND_USER_MESSAGES_SUCCESS'
export const SEND_USER_MESSAGES_FAILURE = 'SEND_USER_MESSAGES_FAILURE'

export const GET_ROOM_MESSAGES = 'GET_ROOM_MESSAGES'
export const GET_ROOM_MESSAGES_SUCCESS = 'GET_ROOM_MESSAGES_SUCCESS'
export const GET_ROOM_MESSAGES_FAILURE = 'GET_ROOM_MESSAGES_FAILURE'
export const GET_ROOM_MESSAGES_CLEAR_ALL = '  GET_ROOM_MESSAGES_CLEAR_ALL'

export const SEND_MESSAGE = 'SEND_MESSAGE'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE'

export const GET_USER_ID = 'GET_USER_ID'
export const GET_USER_ID_SUCCESS = 'GET_USER_ID_SUCCESS'
export const GET_USER_ID_FAILURE = 'GET_USER_ID_FAILURE'

export const GET_ROOMS = 'GET_ROOMS'
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS'
export const GET_ROOMS_FAILURE = 'GET_ROOMS_FAILURE'
export const GET_ROOMS_CLEAR = 'GET_ROOMS_CLEAR'
export const REMOVE_PARTICIPANT_FROM_ROOM = 'REMOVE_PARTICIPANT_FROM_ROOM'
export const ADD_PARTICIPANT_FROM_ROOM = 'ADD_PARTICIPANT_FROM_ROOM'
export const EXIT_FROM_GROUP = 'EXIT_FROM_GROUP'

export const GET_ALL_USER_LIST = 'GET_ALL_USER_LIST'
export const GET_ALL_USER_LIST_SUCCESS = 'GET_ALL_USER_LIST_SUCCESS'
export const GET_ALL_USER_LIST_FAILURE = 'GET_ALL_USER_LIST_FAILURE'
export const GET_ALL_USER_LIST_CLEAR = 'GET_ALL_USER_LIST_CLEAR'
export const SET_ALL_USER = 'SET_ALL_USER'

export const ADD_ROOM_LIST = 'ADD_ROOM_LIST'
export const ADD_ROOM_LIST_SUCCESS = 'ADD_ROOM_LIST_SUCCESS'
export const ADD_ROOM_LIST_FAILURE = 'ADD_ROOM_LIST_FAILURE'
export const ADD_ROOM_LIST_CLEAR = 'ADD_ROOM_LIST_CLEAR'

export const CLEAR_MESSAGE = 'CLEAR_MESSAGEX'
export const SHOW_MESSAGE_INFO = 'SHOW_MESSAGE_INFO'

export const SEND_TOKEN = 'SEND_TOKEN'
export const SEND_TOKEN_SUCCESS = 'SEND_TOKEN_SUCCESS'
export const SEND_TOKEN_FAILURE = 'SEND_TOKEN_FAILURE'

export const UPDATE_GROUP = 'UPDATE_GROUP'
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS'
export const UPDATE_GROUP_FAILURE = 'UPDATE_GROUP_FAILURE'

export const UPDATE_GROUP_ICON = 'UPDATE_GROUP_ICON'
export const UPDATE_GROUP_ICON_SUCCESS = 'UPDATE_GROUP_ICON_SUCCESS'
export const UPDATE_GROUP_ICON_FAILURE = 'UPDATE_GROUP_ICON_FAILURE'
export const UPDATE_GROUP_CLEAR = 'UPDATE_GROUP_CLEAR'

// Reminder Action Type
export const CREATE_REMINDER = 'CREATE_REMINDER'
export const CREATE_REMINDER_SUCCESS = 'CREATE_REMINDER_SUCCESS'
export const CREATE_REMINDER_FAILURE = 'CREATE_REMINDER_FAILURE'
export const ADD_REMINDER_LOCALLY = 'ADD_REMINDER_LOCALLY'

export const GET_REMINDER = 'GET_REMINDER'
export const GET_REMINDER_SUCCESS = 'GET_REMINDER_SUCCESS'
export const GET_REMINDER_FAILURE = 'GET_REMINDER_FAILURE'
export const GET_REMINDER_CLEAR = 'GET_REMINDER_CLEAR'

export const UPDATE_REMINDER = 'UPDATE_REMINDER'
export const UPDATE_REMINDER_SUCCESS = 'UPDATE_REMINDER_SUCCESS'
export const UPDATE_REMINDER_FAILURE = 'UPDATE_REMINDER_FAILURE'
export const UPDATE_REMINDER_CLEAR = 'UPDATE_REMINDER_CLEAR'

export const DELETE_REMINDER = 'DELETE_REMINDER'
export const DELETE_REMINDER_SUCCESS = 'DELETE_REMINDER_SUCCESS'
export const DELETE_REMINDER_FAILURE = 'DELETE_REMINDER_FAILURE'
export const DELETE_REMINDER_CLEAR = 'DELETE_REMINDER_CLEAR'

export const GET_SYSTEM_CONTACTS = 'GET_SYSTEM_CONTACTS'
export const GET_SYSTEM_CONTACTS_SUCCESS = 'GET_SYSTEM_CONTACTS_SUCCESS'
export const GET_SYSTEM_CONTACTS_FAILURE = 'GET_SYSTEM_CONTACTS_FAILURE'
export const GET_SYSTEM_CONTACTS_CLEAR = 'GET_SYSTEM_CONTACTS_CLEAR'
export const CHECK_FOR_APP_CONTACTS = 'CHECK_FOR_APP_CONTACTS'

export const CLEAR_REMINDER_FLAGS = 'CLEAR_REMINDER_FLAGS'

export const STORE_SELECTED_ROOM_START = 'STORE_SELECTED_ROOM_START'
export const STORE_SELECTED_ROOM_SUCCESS = 'STORE_SELECTED_ROOM_SUCCESS'
export const STORE_SELECTED_ROOM_FAILURE = 'STORE_SELECTED_ROOM_FAILURE'
export const STORE_SELECTED_ROOM_CLEAR = 'STORE_SELECTED_ROOM_CLEAR'

export const FORGOT_PASSWORD_START = 'FORGOT_PASSWORD_START'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE'

export const ACCEPT_REMINDER_START = 'ACCEPT_REMINDER_START'
export const ACCEPT_REMINDER_SUCCESS = 'ACCEPT_REMINDER_SUCCESS'
export const ACCEPT_REMINDER_FAILURE = 'ACCEPT_REMINDER_FAILURE'

export const CREATE_ANNOUNCEMENT = 'CREATE_ANNOUNCEMENT'
export const CREATE_ANNOUNCEMENT_SUCCESS = 'CREATE_ANNOUNCEMENT_SUCCESS'
export const CREATE_ANNOUNCEMENT_FAILURE = 'CREATE_ANNOUNCEMENT_FAILURE'
export const CREATE_ANNOUNCEMENT_CLEAR = 'CREATE_ANNOUNCEMENT_CLEAR'

export const GET_ANNOUNCEMENT = 'GET_ANNOUNCEMENT'
export const GET_ANNOUNCEMENT_SUCCESS = 'GET_ANNOUNCEMENT_SUCCESS'
export const GET_ANNOUNCEMENT_FAILURE = 'GET_ANNOUNCEMENT_FAILURE'
export const ADD_LOCALLY = 'ADD_LOCALLY'

export const UPDATE_ANNOUNCEMENT = 'UPDATE_ANNOUNCEMENT'
export const UPDATE_ANNOUNCEMENT_SUCCESS = 'UPDATE_ANNOUNCEMENT_SUCCESS'
export const UPDATE_ANNOUNCEMENT_FAILURE = 'UPDATE_ANNOUNCEMENT_FAILURE'
export const UPDATE_ANNOUNCEMENT_CLEAR = 'UPDATE_ANNOUNCEMENT_CLEAR'

export const ARCHIVE_ANNOUNCEMENT = 'ARCHIVE_ANNOUNCEMENT'
export const ARCHIVE_ANNOUNCEMENT_SUCCESS = 'ARCHIVE_ANNOUNCEMENT_SUCCESS'
export const ARCHIVE_ANNOUNCEMENT_FAILURE = 'ARCHIVE_ANNOUNCEMENT_FAILURE'
export const ARCHIVE_ANNOUNCEMENT_CLEAR = 'ARCHIVE_ANNOUNCEMENT_CLEAR'

export const CLEAR_ANNOUNCEMENT_FLAGS = 'CLEAR_ANNOUNCEMENT_FLAGS'

export const DELETE_MESSAGE = 'DELETE_MESSAGE'
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS'
export const DELETE_MESSAGE_FAILURE = 'DELETE_MESSAGE_FAILURE'

export const GET_CAREID = 'GET_CAREID'
export const GET_CAREID_SUCCESS = 'GET_CAREID_SUCCESS'
export const GET_CAREID_FAILURE = 'GET_CAREID_FAILURE'

export const ENTER_IN_ROOM = 'ENTER_IN_ROOM'
export const ENTER_IN_ROOM_SUCCESS = 'ENTER_IN_ROOM_SUCCESS'
export const ENTER_IN_ROOM_FAILURE = 'ENTER_IN_ROOM_FAILURE'

export const CHECK_VERIFICATION_CODE_FLAG_FALSE = 'CHECK_VERIFICATION_CODE_FLAG_FALSE'
export const UPDATE_STORED_USER = 'UPDATE_STORED_USER'

export const CHECK_EMAIL_EXIST = 'CHECK_EMAIL_EXIST'
export const CHECK_EMAIL_EXIST_SUCCESS = 'CHECK_EMAIL_EXIST_SUCCESS'
export const CHECK_EMAIL_EXIST_FAILURE = 'CHECK_EMAIL_EXIST_FAILURE'
export const CHECK_EMAIL_EXIST_CLEAR = 'CHECK_EMAIL_EXIST_CLEAR'

export const SOCKET_CONNECTION = 'SOCKET_CONNECTION'