import { Platform } from 'react-native'

const enums = {
  CENTER: 'center',
  FONTAWESOME_MEDIUM: Platform.OS === 'ios' ? 'FontAwesome' : 'fontawesome-s',
  FONTAWESOME_REGULAR: Platform.OS === 'ios' ? 'FontAwesome' : 'fontawesome-r',
  FONTAWESOME_BOLD: Platform.OS === 'ios' ? 'FontAwesome' : 'fontawesome-b',
  // HELVETICA_PRIMARY: 'HelveticaNeue_M',
  // HELVETICA_BOLD: 'Helvetica_B',
  ROW: 'row',
  COLUMN: 'column',
  BOLD: 'bold',
  RIGHT: 'right',
  END: 'flex-end',
  START: 'flex-start',
  SPACE_B: 'space-between',
  ABSOLUTE: 'absolute',
  WRAP: 'wrap',
  FACEBOOK: 'facebook',
  CONTACT: 'contact',
  GOOGLE: 'google',
  LINKEDIN: 'linkedIn',
  PADDING: 'padding',
  HOME: 'home',
  CONTACTLIST: 'contactList',
  NEWGROUP: 'newGroup',
  NEWCHAT: 'newChat',
  ITALIC: 'italic',
  NORMAL: 'normal',
  STRETCH: 'stretch',
  CONTAIN: 'contain',
  COVER: 'cover',
  REPEAT: 'repeat',
  HOMEPROFILE: 'homeProfile',
  LARGE: 'large',
  RELATIVE: 'relative',

  //group updateTypes
  ICON: 'ICON',
  ADD_PARTICIPANTS: 'ADD_PARTICIPANTS',
  REMOVE_PARTICIPANTS: 'REMOVE_PARTICIPANTS',
  ROOM_TITLE: 'ROOM_TITLE',
  LEAVE_GROUP: 'LEAVE_GROUP',
  BLOCK_USER: 'BLOCK_USER',
  UNBLOCK_USER: 'UNBLOCK_USER',

  //room types and ids
  GROUP: 'GROUP',
  GROUPID: 0,
  PRIVATE: 'PRIVATE',
  PRIVATEID: 1,

  //message types and ids
  TEXT: 'TEXT',
  TEXTID: 0,
  SYSTEM: 'SYSTEM',
  SYSTEMID: 1,
  MEDIA: 'MEDIA',
  MEDIAID: 2,
  REMINDER: 'REMINDER',
  REMINDERID: 3,
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  ANNOUNCEMENTID: 4,

  //media message types and ids
  DOCUMENT: 'DOCUMENT',
  DOCUMENTID: 0,
  VCARD: 'VCARD',
  VCARDID: 1,
  VIDEO: 'VIDEO',
  VIDEOID: 2,
  AUDIO: 'AUDIO',
  AUDIOID: 3,
  IMAGE: 'IMAGE',
  IMAGEID: 4,
  FILE: 'FILE',
  FILEID: 5,
}

export default enums